import type { Member, Transfer } from "./types";

export const mockData: { members: Member[]; transfers: Transfer[] } = {
  members: [
    { id: "m1", name: "Aanya Pillai", role: "Design Lead", initials: "AP" },
    { id: "m2", name: "Rohan Mehta", role: "Engineering", initials: "RM" },
    { id: "m3", name: "Sara Thomas", role: "Marketing", initials: "ST" },
    { id: "m4", name: "Vikram Nair", role: "Operations", initials: "VN" },
    { id: "m5", name: "Priya Iyer", role: "Product", initials: "PI" },
  ],
  transfers: [
    {
      id: "t1",
      title: "Q3 Brand Assets - Final",
      senderId: "m1",
      recipientIds: ["m2", "m3"],
      files: [
        { name: "Logo_Pack.zip", size_mb: 145 },
        { name: "Brand_Guidelines.pdf", size_mb: 8 },
        { name: "Social_Templates.fig", size_mb: 22 },
      ],
      createdDaysAgo: 2,
      expiresInDays: 5,
      status: "active",
      favorited: true,
    },
    {
      id: "t2",
      title: "Investor Deck v4",
      senderId: "m5",
      recipientIds: ["m4"],
      files: [{ name: "Investor_Deck_v4.pptx", size_mb: 34 }],
      createdDaysAgo: 6,
      expiresInHours: 6,
      status: "expiring_soon",
      favorited: false,
    },
    {
      id: "t3",
      title: "Client Contract - Signed",
      senderId: "m4",
      recipientIds: ["m1", "m5"],
      files: [
        { name: "Contract_Signed.pdf", size_mb: 2 },
        { name: "Annex_A.pdf", size_mb: 1 },
      ],
      createdDaysAgo: 9,
      expiredDaysAgo: 2,
      status: "expired",
      favorited: false,
    },
    {
      id: "t4",
      title: "Site Photography - Raw",
      senderId: "m2",
      recipientIds: ["m1"],
      files: [{ name: "Site_Photos_Raw.zip", size_mb: 1228 }],
      createdDaysAgo: 0,
      expiresInDays: 7,
      status: "active",
      favorited: false,
    },
    {
      id: "t5",
      title: "Onboarding Video Drafts",
      senderId: "m3",
      recipientIds: ["m2", "m4", "m5"],
      files: [
        { name: "cut1.mp4", size_mb: 320 },
        { name: "cut2.mp4", size_mb: 290 },
        { name: "vo_track.wav", size_mb: 18 },
        { name: "captions.srt", size_mb: 0.1 },
      ],
      createdDaysAgo: 1,
      expiresInDays: 3,
      status: "active",
      favorited: false,
    },
    {
      id: "t6",
      title: "Vendor Quotes - June",
      senderId: "m4",
      recipientIds: ["m5"],
      files: [
        { name: "Quote_VendorA.pdf", size_mb: 1.5 },
        { name: "Quote_VendorB.pdf", size_mb: 2 },
        { name: "Quote_VendorC.pdf", size_mb: 1.2 },
      ],
      createdDaysAgo: 4,
      disabled: true,
      status: "disabled",
      favorited: false,
    },
    {
      id: "t7",
      title: "Team Offsite Photos",
      senderId: "m1",
      recipientIds: ["m2", "m3", "m4", "m5"],
      files: [{ name: "Offsite_Photos.zip", size_mb: 640 }],
      createdDaysAgo: 3,
      expiresInDays: 10,
      status: "active",
      favorited: true,
    },
    {
      id: "t8",
      title: "API Documentation Export",
      senderId: "m2",
      recipientIds: ["m5"],
      files: [{ name: "api-docs-export.pdf", size_mb: 4 }],
      createdDaysAgo: 10,
      expiredDaysAgo: 5,
      status: "expired",
      favorited: false,
    },
    {
      id: "t9",
      title: "Press Kit - Launch",
      senderId: "m3",
      recipientIds: ["m1", "m4"],
      files: [
        { name: "Hero_Image_1.jpg", size_mb: 12 },
        { name: "Hero_Image_2.jpg", size_mb: 14 },
        { name: "Product_Shot.jpg", size_mb: 9 },
        { name: "Press_Release.pdf", size_mb: 1 },
        { name: "Founder_Headshot.jpg", size_mb: 6 },
      ],
      createdDaysAgo: 5,
      expiresInHours: 18,
      status: "expiring_soon",
      favorited: false,
    },
    {
      id: "t10",
      title: "Payroll Backup - June",
      senderId: "m5",
      recipientIds: ["m4"],
      files: [{ name: "payroll_backup_june.xlsx", size_mb: 3 }],
      createdDaysAgo: 1,
      expiresInDays: 1,
      status: "active",
      favorited: false,
    },
  ],
};

